### ISSUE TITLE
Bug: receiving the following error with revision history

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#103]
## Notes
Save Applications: vendor.x.bundle.js:1 ERROR Error: Cannot find form control with name: controlNumber.
	- shouldn’t be looking for a control number until sent to SUDS

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
I think this is resolved?

**Comment by hannahkane** [comment]
I'm not sure how to try to reproduce this. @lauraGgit, can you please add steps to reproduce if you recall?

**Comment by lauraGgit** [comment]
I think this is either closed by #161 or resolved so closing.
