### ISSUE TITLE
As a special use applicant, I should see my event name when I am editing an applicaition

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#104]
## Notes
Populate Event Name on editing a hold application

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
Can't verify until #161 is resolved

**Comment by hannahkane** [comment]
Actually, closing because this is essentially duped by 161
