### ISSUE TITLE
As a noncommericial applicant i should not be able to submit an application with fewer than 75 combined particiapants and spectators.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#116]
## Notes
Need validation on the 2 form fields for noncommercial that the number of attendees (participants/spectators) combined would be more than 75. or they should be notified that they don't need a permit for their activity

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@lauraGgit I was still able to submit an application with less than 75 combined attendees

**Comment by lauraGgit** [comment]
@msadakFS, we may have to pair, because i'm unable to replicate.

**Comment by msadakFS** [comment]
@lauraGgit just submitted another one, here's the screenshot from the email confirmation. 

![image](https://user-images.githubusercontent.com/39954421/44158728-0fb8f000-a07b-11e8-9111-7dfd985617a2.png)

**Comment by lauraGgit** [comment]
blocked because of docker config tweaks in #320

**Comment by msadakFS** [comment]
Test looked good, I was unable to process application with less than 75 participants.
