### ISSUE TITLE
Canceling an application from the application list view fails

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#118]
Steps to reproduce:

1. Log in as a public user and submit a SU application
2. Log in as an admin and mark the application on hold
3. Log in as the public user, click on "View applications"
4. Click the "Cancel" button next to the application and confirm in the dialog box

**Expected result**: See a success message and the item should be removed from the list

**Actual result**: This error message: "There was an error cancelling your application. Please try again." Item still appears in list, though without the status or Cancel button visible (see top item in the screenshot below). Note the status and Cancel button reappear upon refresh.

<img width="1043" alt="screen shot 2018-05-03 at 11 14 49 am" src="https://user-images.githubusercontent.com/8389648/39595046-3381fb26-4ec3-11e8-8ce6-9c415b0f70fb.png">

**Comment by hannahkane** [comment]
@lauraGgit - To clarify, is there a workaround for this? Can applications be canceled from the detail view, for example?

**Comment by hannahkane** [comment]
@lauraGgit - I edited the title of this issue and added what I assume is the value, but can you verify, please?

**Comment by lauraGgit** [comment]
validated today

**Comment by lauraGgit** [comment]
Note: you can successfully cancel from the details page

**Comment by lauraGgit** [comment]
Looks like this method: https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/applications/permit-application-list/permit-application-list.component.ts#L86

but its a bit confusing how the detail view handles the cancel - it seems like it would be here https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/applications/permit-application-view/permit-application-view.component.ts#L20

**Comment by msadakFS** [comment]
I am getting the error:
![image](https://user-images.githubusercontent.com/39954421/42691195-ad02ecea-866c-11e8-9433-ca38b476563d.png)
