### ISSUE TITLE
As a temp outfitter applicant, I should get a sidebar validation checkmark if i have a valid promotional website.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#119]
## Notes
Should get a checkmark if you have a valid promotional website

## Acceptance Criteria
- [ ] If the applicant have submitted a valid advertising website or content then they should have a valid section.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@lauraGgit I am able to generate the check mark and submit an app with an invalid promotional site

**Comment by msadakFS** [comment]
@lauraGgit At this point, everything seems to work no matter what website you enter in the box. Is that supposed to be the functionality or is there supposed to be some sort of automated check to validate whether the website is legit? Or, is the SUA supposed to go out and navigate to the applicants site?

**Comment by lauraGgit** [comment]
@msadakFS yes, we only assume that it is a *.* because we don't want to assume `www` or that they will add `https://`
