### ISSUE TITLE
consider refactoring to node email template

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#143]
## Notes
bring out more of the custom email functionality and move to an existing library like 
https://github.com/niftylettuce/email-templates

or at a minimum use juice directly
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
From @lauraGgit: Refactored into a base HTML template with separate style file, and using `juice` to render inline css as part of #213. This minimal implementation should suffice and reduce unnecessary dependencies. It may warrant future consideration to create a method to generate tables more consistently.
