### ISSUE TITLE
Add Digital Analytics Program identifiers on frontend

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#173]
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@lauraGgit Can you provide some details on what this means. Thank you.

**Comment by hursey013** [comment]
I can take care of this one if it's helpful. The [Digital Analytics Program (DAP)](https://digital.gov/dap/) is web analytics for federal agencies. It feeds into https://analytics.usa.gov/, but more importantly it gives you access to a dashboard where you can access more in-depth stats.

It looks like DAP is already included across https://www.fs.fed.us/ so this would just be a matter of making sure the same code snippet is included within all of our pages as well.

**Comment by msadakFS** [comment]
@hursey013 As a PO, what exactly do I need to review on this issue? Can it be moved to close?

**Comment by lauraGgit** [comment]
Confirmed on staging
