### ISSUE TITLE
As a user, I should be able to report a bug or feature request, so that my voice is heard

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#176]
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
Noting that we'll be fleshing out the requirements for this next week in Salt Lake City when we discuss the customer support plan

**Comment by msadakFS** [comment]
Refer to notes from SLC meeting: https://docs.google.com/document/d/1_PFpV0OvQTE_lvOPWLN4lgWJ4IsWxqQ6c_vvP-QS6I4/edit?ts=5b44ce77#

**Comment by msadakFS** [comment]
Covered by issue #273
