### ISSUE TITLE
Bug when selecting View Applications

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-permit-platform#210]
## Notes
Submitting a non-commercial permit application then selected the View Application option after submission. Received the following error:
![ePermit_ViewApp_error.PNG](https://images.zenhubusercontent.com/5b16b7b789d5dc41604fe1e0/0c850abb-8273-4d00-a8cd-e28fd8622e03)

## Acceptance Criteria
When selecting View Applications, I see all applications that I have applied for and their status.

**Comment by lauraGgit** [comment]
We were in the middle of restaging the application, and so I wouldn't be surprised if that affected you. Let me know if you're still seeing this.

**Comment by hannahkane** [comment]
I am not able to reproduce this. @msadakFS - would you mind running through the steps again to see if you can reproduce?

**Comment by msadakFS** [comment]
I now longer have the issue. I was able to submit an application while signed in with my FS account via eAuth. That may be a separate issue. I was not able to recreate the bug while using my login.gov account.
