### ISSUE TITLE
As a special use applicant, after being prompted to log in from the Apply buttons, I am directed to the relevant application, rather than taking them back to the Guide page.

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-permit-platform#215]
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
@msadakFS can we close this?

**Comment by msadakFS** [comment]
Yes we can
