### ISSUE TITLE
Clicking links to return to homepage does not update page title

### ISSUE THREAD

**Issue by hursey013** [18F/fs-permit-platform#231]
## Notes
When navigating to various pages and clicking buttons, links, and breadcrumbs that return you to the homepage, the page title is not updated to reflect the current page, instead it continues to display the title for previous page.

From the homepage, click the `Click here to learn more about this permit.` link. Scroll to the bottom of the page and click `Back to permits`. Upon returning to homepage observe the title to be `Noncommercial permit FAQs`.

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Potential issue with 508 compliance.
