### ISSUE TITLE
Error when trying to route back into FS online permits after log in via Login.gov

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-permit-platform#237]
![site error](https://user-images.githubusercontent.com/39954421/41913542-331c11ee-7916-11e8-9432-9fab228eabe2.JPG)
## Notes
When trying to log in via login.gov on https://openforest.fs.usda.gov/ , I get routed to a blank site that states "404 Not Found: Requested route ('forest-service-epermit.app.cloud.gov') does not exist." This happens after I enter in my login.gov username and password and hit the continue button (see the attached graphic)![login link error.JPG](https://images.zenhubusercontent.com/5b16b7b789d5dc41604fe1e0/3114c4aa-54c5-4f6b-9286-3b3316316e59)

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
yes, this is not yet enabled for our new url. we will be able to fix this when we address #150.
