### ISSUE TITLE
As a user, I would like to be confident in the integrity of the application, even when there is an unmediated vulnerability 

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#238]
## Notes
right now the nightly redeploy will fail when a vulnerabilty is found on our dependency scanner `snyk`, which means that the nightly refresh of the site (cf recycle) will not go. This means that we have inconsistent  redeployments. This can  be easily refactored so that the two occur independently of one another.

## Acceptance Criteria
- [ ] The nightly re-deployment will occur every night, (regardless of snyk issues)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@lauraGgit is this necessary for the ATO?

**Comment by lauraGgit** [comment]
Not necessarily, but from a security perspective makes sense to do before production.

**Comment by lauraGgit** [comment]
now made part of 229
