### ISSUE TITLE
As a user, I want to know that I am being redirected to login.gov when I select noncommercial permit and temporary guide from the "help me pick" page.

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-permit-platform#239]
## Notes
Add login.gov info to the "find a permit" wizard flow (https://forest-service-trees-staging.app.cloud.gov/help-me-pick/7 and https://forest-service-trees-staging.app.cloud.gov/help-me-pick/8)

![image.png](https://images.zenhubusercontent.com/5b16b7b789d5dc41604fe1e0/e1d36190-5eb1-40e4-9814-e7828a5549d8)

## Acceptance Criteria
- use the same treatment used on the "learn more" pages - see #233  

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@hursey013 @hannahkane I am not seeing any changes that have been applied. I still see:
![image](https://user-images.githubusercontent.com/39954421/42689931-0982c332-8668-11e8-9982-556ea3583543.png)
rather than:

![image](https://user-images.githubusercontent.com/39954421/42689917-f8e86216-8667-11e8-92c0-ad9a8a825114.png)

**Comment by lauraGgit** [comment]
@msadakFS changes are not applied until we close out a pull request. In this case #270 is the change request for the code to change it and @hursey013 has posted screenshots of what this will look like.

**Comment by msadakFS** [comment]
Ah, thank you! I figured I was missing something this morning (or getting ahead of myself) while going through the list this morning. @lauraGgit @hursey013

**Comment by msadakFS** [comment]
@hursey013 @hannahkane Should we be consistent and have the button like the one above. Right now I see the graphic below.
![image](https://user-images.githubusercontent.com/39954421/42840348-27bd00f8-89cc-11e8-8090-c2f4ac311438.png)

**Comment by hannahkane** [comment]
I'll defer to @hursey013 on the button styles
