### ISSUE TITLE
As an organizational noncommercial group use applicant, I should not see "application errors" if I have submitted all the org fields

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#248]
## Notes
On the noncommercial group use permit form, if you apply as an organization, you will get errors, even when you've completed all the fields, because it is validating against the `inidividual` applicant address fields. 

## Acceptance Criteria
- [ ] nc organizations can successfully submit an application without completing the individual information

## Tasks
- [ ] update the noncommercial applicant address conditionals for organizational applicants to remove those errors

## Organization address view 👍 
![image](https://user-images.githubusercontent.com/5840989/42111546-d51cbfcc-7bb2-11e8-9289-a788b8684007.png)

## Individual - should not care if org is selected
![image](https://user-images.githubusercontent.com/5840989/42111585-ec486048-7bb2-11e8-9c49-523e6258d76b.png)

**Comment by aaronburk** [comment]
Seems to be relatively high priority

**Comment by hursey013** [comment]
@lauraGgit  I'm actually having trouble recreating this. I've filled out a few non-commercial fields locally and submitted them without issue. I'm not sure if it is tied to the Individual address fields, I think those get validation added and removed when you toggle the org type so those actually may be working as expected. Will continue digging!

**Comment by lauraGgit** [comment]
If Individual user:
- address == primary address

If org user:
      - if "Permit holder address is same as organization address." is checked:
          - copy organization address to primary address before submission
     - else:
          ensure that primary address fields are completed by user
