### ISSUE TITLE
outiftter guide Upload option under  Applicant is confusing in Step 1

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-permit-platform#255]
## Notes
Under Outfitter guide as individual there is no upload option in **"Step 1: Applicant Information" for individual .  Under  Step 1: Applicant Information for corporation it is clear guidance "Provide a copy of your state certificate of good standing" for the LLC, PArtnership, State  Govt, and non profit there is an upload option (with no guidance what to upload.  For Local Gov tghere is no upload option for step 1
 
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
Is there supposed to be an upload for Individuals? What would they be uploading? 

Good catch on not having a field label for the LLC, partnership, state govt, and nonprofit types, and not having the field or label for local govt. I believe this is a recently introduced bug.

**Comment by aaronburk** [comment]
I'm not sure if there should be an upload for individuals?  I just noticed there was guidance missing/inconsistent. Maybe we can check with previous versions?

**Comment by lauraGgit** [comment]
@aaronburk @hannahkane you're correct, when we updated the orgTypes, it broke this:
https://github.com/18F/fs-permit-platform/blob/8c0eae0ce417d5148f2600041106a27712724d6d/frontend/src/app/application-forms/temporary-outfitters/temporary-outfitters.component.ts#L139

- will need to add a test to check that this appears.
- local govts do not a appear to need evidence of good standing.

**Comment by hannahkane** [comment]
Moving this to top of backlog

**Comment by msadakFS** [comment]
@hannahkane @hursey013 The hard copy form requires a copy of the state certificate of good standing for Individuals and a copy of IRS Form 990.
