### ISSUE TITLE
fix nightly circle build

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#258]
## Notes
https://circleci.com/gh/18F/fs-middlelayer-api/489?utm_campaign=build-failed&utm_medium=email&utm_source=notification

- fix the checkout

## Acceptance Criteria
- [ ] the nightly workflow passes.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hursey013** [comment]
I think this just requires a typo fix which I made [here](https://github.com/18F/fs-middlelayer-api/commit/63ad3f64b95c728686e699126bb9e43232d592e9), need to get it merged into `master` though to test with CircleCI.

**Comment by lauraGgit** [comment]
@hursey013 ah looks good, going to merge to master
