### ISSUE TITLE
as a user, i'd like to see changes faster (move dev artifacts to wiki)

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#260]
## Notes
move the user research artifacts to the wiki repository https://github.com/18F/fs-online-permitting so that the checkout process on circle / cloud.gov is faster

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@lauraGgit I noticed that the User Research artifacts on the Wiki date back to 2017. Have artifacts been created and not posted since? I may need you to explain a little further to clarify the connection between the user research artifacts and the Circle/Cloud.gov checkout process.

**Comment by msadakFS** [comment]
@lauraGgit will move the wiki directory out of the platform repository to the project/info repository
