### ISSUE TITLE
As a user I want to call the District/Unit office directly so that I receive personal assistance when needed

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-permit-platform#273]
## Notes
Unit phone number is clearly visible on website

## Acceptance Criteria
- [ ] User can easily locate contact number when needed 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
At contact number to Learn More page

**Comment by hursey013** [comment]
@msadakFS do we have the actual contact information that we would like listed on the `Learn more` page, or for now should it be a placeholder like it is when an application is submitted?

![screen shot 2018-07-26 at 3 03 23 pm](https://user-images.githubusercontent.com/1178494/43282859-43008ba8-90e5-11e8-87c0-c02a96c5bfc6.png)

**Comment by lauraGgit** [comment]
is this not a duplicate of #165? it looks like for that we just want the contact name on that card?

**Comment by hursey013** [comment]
@lauraGgit my understanding of this card is that we want to add the same information from https://github.com/18F/fs-permit-platform/issues/165 to the Learn More pages as well

**Comment by lauraGgit** [comment]
I think `our National Forests` sets a more user-friendly tone.

**Comment by msadakFS** [comment]
I read it as this would be covered under 165. I moved it out of Blocked and into the Sprint.
