### ISSUE TITLE
As a SUA, I should see the security ID / managing org ID associated with an existing contact in SUDS, so that I know the contact is associated with my forest

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#279]
## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
According to NRM we can only supply the managing Org to the application, which we are already doing. So will close.
