### ISSUE TITLE
As an outfitter/guide, I can submit a business license or certificate of good standing.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-permit-platform#70]
## Notes
In Washington state, outfitters do not need to submit a copy of their certificate of good standing, despite what the OMB-approved form says. Outfitters instead submit a business license.

Severity: High - prevents accurate form submissions
Difficulty of remediation: Low - probably only requires a copy change

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
I'm thinking this can be resolved with a simple copy change. On the outfitter/guide application, if the user selects Corporation or Limited Liability Company, they are prompted to submit a certificate of good standing. The field label here could be modified to read, "Provide a copy of your state certificate of good standing or a business license."

<img width="532" alt="screen shot 2018-06-13 at 3 51 42 pm" src="https://user-images.githubusercontent.com/8389648/41382576-9176fbea-6f21-11e8-8f29-561f4e03b246.png">

Does that seem like it would work?

**Comment by msadakFS** [comment]
@hannahkane That makes sense. I wonder how many states have that exception (thinking big picture)? Other states use different terminology, for instance, a certificate of good standing in WI is equivalent to their "certificate of status."

**Comment by hannahkane** [comment]
Good call. Is there a generic term we could use that would be easily understood everywhere?

**Comment by hannahkane** [comment]
Noting that we can't change the field label without doing some Paperwork Reduction Act-related stuff, so we might want to think of a solution that modifies the help text only. (@lauraGgit - if I understood you correctly, we can modify the help text, right? Is the "File must be in .pdf, .doc..." part the help text?)

**Comment by lauraGgit** [comment]
@hannahkane yes, we can modify the help text as much as we'd like!

**Comment by msadakFS** [comment]
Can update help desk without violating PRA requirements

**Comment by hursey013** [comment]
@msadakFS just wanted to confirm the help text change when you have a moment. I'm planning on updating `Provide a copy of your state certificate of good standing.` to `Provide a copy of your state certificate of good standing or a business license.` - does that sound right?

**Comment by lauraGgit** [comment]
@hursey013 @msadakFS i think we might want to check with MBS about this - given that the conflict of the OMB approved form, what are we asking for could be a bit confusing.

**Comment by msadakFS** [comment]
We wouldn't change the ePermit application form text, but the help text correct. Or is that considered one of the same?

**Comment by lauraGgit** [comment]
Yes, that's right, we can change the help text, but the field text is set.

**Comment by hannahkane** [comment]
@msadakFS - Would love to get Sue's thoughts on that. I don't know that we can expect applicants to know what their state equivalent is.

**Comment by msadakFS** [comment]
@hannahkane I did send Sue an email on this. Sue will not be back until Tuesday.

**Comment by msadakFS** [comment]
@hannahkane @lauraGgit Sue stated that she prefers "Provide a copy of your certificate of good standing or state equivalent"
