### ISSUE TITLE
As an outfitter/guide, I can upload a file to show where my trips will go instead of using the text box.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-permit-platform#71]
## Notes
This will also affect the [middle layer](https://github.com/18F/fs-middlelayer-api).
Severity: High - prevents accurate form submissions
Difficulty of remediation: Medium - would require adding a field in the middle layer and intake module

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
@lauraGgit @tadhg-ohiggins - do we need this issue, or is https://github.com/18F/fs-middlelayer-api/issues/79 adequate? They seem duplicative to me.

**Comment by lauraGgit** [comment]
@hannahkane this does look like a duplicate, I recommend closing.
