### ISSUE TITLE
As a special use administrator, I can click the link in an application email and be redirected to that application’s details.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-permit-platform#72]
## Notes
When a SUA clicks a permit application link in email and authenticates, she is redirected to an empty application list screen. 

Severity: Severe - prevents application approval
Difficulty of remediation: Unknown

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
@lauraGgit - is there a way for @msadakFS and I to test this? For example, can we be temporarily added to the recipients list for SUA email notifications?

**Comment by lauraGgit** [comment]
@hannahkane I just tested this and it appears that this error is no longer valid. Closing for now.
