### ISSUE TITLE
As a special use administrator, I can easily read application answers that include line breaks.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-permit-platform#74]
## Notes
In the ePermit application details screen, longer text fields are missing returns. Text entries separated by returns are jammed together and hard to read.

Severity: Moderate - confuses special use administrators
Difficulty of remediation: Low - probably just making sure input is appropriately cleaned?

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
This is a duplicate of the middlelayer #78.
