### ISSUE TITLE
As a special use administrator, I learn the SUDS ID number of an application after I approve it.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-permit-platform#75]
## Notes
After a SUA presses the “approve” button, she should see the SUDS ID of the newly created SUDS application. Without this number, special use administrators must page through every open SUDS application to find the new number. (The “ePermit” ID is not visible to SUAs in SUDS.)

Severity: Moderate - confuses special use administrators
Difficulty of remediation: Unknown

## Acceptance Criteria
- [ ] SUAs can easily find SUDS ID on an approved application
- [ ] Users without SUA permissions cannot see the SUDS ID

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
What's the best way for a special use administrator receives the SUDS ID? Does the ID display on a page in ePermit, get emailed, etc.? Are there any technical limitation on what we can do? @lauraGgit

**Comment by hannahkane** [comment]
@lauraGgit - even after reading the user research notes, I still don't know the answer to @msadakFS's question above. Are we going to be able to immediately display the SUDS ID to the user from within ePermit? It sounds like there's no way to link directly to the record, so they'll still have to search for it manually, is that right?

**Comment by lauraGgit** [comment]
With the [PR FS-Middlayer #121](https://github.com/18F/fs-middlelayer-api/pull/121) We updated the ID in SUDS to be the following `EP-`+`ForestCode`+`applicationId`.

I don't know from the notes, but I think the following place might makes sense: (but on the success)
![image](https://user-images.githubusercontent.com/5840989/41681683-61273b6c-74a3-11e8-9409-24823fe21c31.png)

**Comment by hannahkane** [comment]
Does that mean they can only see it when the page is displaying the Success message? I feel like they should be able to come back to the Detail page later and find the ID.

**Comment by lauraGgit** [comment]
here would be a success image:
![image](https://user-images.githubusercontent.com/5840989/41686822-7f53387e-74b3-11e8-92de-03dc36261faf.png)

**Comment by hannahkane** [comment]
Yeah, I don't think it belongs on the success message itself. I think it needs to always be accessible from the detail page (once it's been created).

**Comment by hursey013** [comment]
How is the `Application identification number` (or "ePermit" ID) used by special use folks? Is it necessary to display at all? Alternatively, once a permit is approved and there is a SUDS ID displayed, can we hide the Application ID?
